require "options"
require "keymappings"
require "plugins"
require "colourscheme"

require "utils"
require "version-control"
require "completion"
require "searching"
require "lsp"
require "syntax-highlighting"
require "tabline"
require "commenting"
