# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

[config]
plugins_dir = "plugin-rocks/"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.4" # rocks.nvim can also manage itself :D
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.2"
"comment.nvim" = "0.8.0"
nvim-ts-context-commentstring = "scm"
"dial.nvim" = "0.4.0"
"indent-blankline.nvim" = "3.8.6"
treesj = "scm"
"ssr.nvim" = "scm"
nvim-surround = "2.1.5"
"plenary.nvim" = "scm"
"toggleterm.nvim" = "2.13.1"

[plugins.nvim-autopairs]
git = "https://github.com/windwp/nvim-autopairs"
rev = "3d02855468f94bf435db41b661b58ec4f48a06b7"

[plugins.catpuccin]
config = "plugin-rocks/catppuccin"
git = "https://github.com/catppuccin/nvim"
rev = "v1.9.0"

[plugins.vim-easy-align]
git = "https://github.com/junegunn/vim-easy-align"
rev = "2.10.0"

[plugins.vim-matchup]
git = "https://github.com/andymass/vim-matchup"
rev = "v0.7.3"

[plugins.undotree]
git = "https://github.com/mbbill/undotree"
rev = "2556c6800b210b2096b55b66e74b4cc1d9ebbe4f"

[plugins."refactoring.nvim"]
git = "https://github.com/theprimeagen/refactoring.nvim"
rev = "2db6d378e873de31d18ade549c2edba64ff1c2e3"
