# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

import = [
  "rocks-picker.toml",
  "rocks-lsp.toml",
  "rocks-completion.toml",
  "rocks-snippets.toml",
  "rocks-debugging.toml",
  "rocks-database.toml",
]

[config]
plugins_dir = "plugin-rocks/"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[dev]
path = "~/repos"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.4" # rocks.nvim can also manage itself :D
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.2"
"rocks-dev.nvim" = "1.7.0"
"comment.nvim" = "0.8.0"
"dial.nvim" = "0.4.0"
"indent-blankline.nvim" = "3.8.6"
treesj = "scm"
"ssr.nvim" = "scm"
nvim-surround = "2.1.5"
"plenary.nvim" = "scm"
"toggleterm.nvim" = "2.13.1"
"which-key.nvim" = "3.15.0"
"telescope.nvim" = "scm"
"heirline.nvim" = "1.0.7"
nvim-web-devicons = "0.100"
"aerial.nvim" = "2.4.0"
"substitute.nvim" = "2.0.0"
nvim-bqf = "1.1.1"
"gitsigns.nvim" = "0.9.0"
"obsidian.nvim" = "3.9.0"
"colortils.nvim" = "1.2.0"
auto-session = "2.5.0"
neogen = "2.20.0"
"render-markdown.nvim" = "7.9.0"
"trouble.nvim" = "3.7.0"

[plugins.nvim-autopairs]
git = "https://github.com/windwp/nvim-autopairs"
rev = "3d02855468f94bf435db41b661b58ec4f48a06b7"

[plugins.catpuccin]
config = "plugin-rocks/catppuccin"
git = "https://github.com/catppuccin/nvim"
rev = "v1.9.0"

[plugins.vim-easy-align]
git = "https://github.com/junegunn/vim-easy-align"
rev = "2.10.0"

[plugins.vim-matchup]
git = "https://github.com/andymass/vim-matchup"
rev = "v0.7.3"

[plugins.undotree]
git = "https://github.com/mbbill/undotree"
rev = "2556c6800b210b2096b55b66e74b4cc1d9ebbe4f"

[plugins."refactoring.nvim"]
git = "https://github.com/theprimeagen/refactoring.nvim"
rev = "2db6d378e873de31d18ade549c2edba64ff1c2e3"

[plugins."roslyn.nvim"]
git = "https://github.com/seblj/roslyn.nvim"
# 322e5295d3cfe7400954ca1154fb4aff5b2aadfe = Pinned rev in old config
rev = "85aca5d48ddf8ada4e010ee9fa4d43c77ebf68c9"

[plugins."cheatsheet.nvim"]
git = "https://github.com/sudormrfbin/cheatsheet.nvim"
rev = "9716f9aaa94dd1fd6ce59b5aae0e5f25e2a463ef"

[plugins.nvim-treesitter]
git = "https://github.com/nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"

[plugins.nvim-ts-context-commentstring ]
git = "https://github.com/joosepalviste/nvim-ts-context-commentstring"
rev = "1b212c2eee76d787bbea6aa5e92a2b534e7b4f8f"

[plugins.nvim-ts-autotag]
git = "https://github.com/windwp/nvim-ts-autotag"
rev = "1cca23c9da708047922d3895a71032bc0449c52d"

[plugins.nvim-treesitter-textobjects]
git = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects"
rev = "ad8f0a472148c3e0ae9851e26a722ee4e29b1595"

[plugins.vim-abolish]
git = "https://github.com/tpope/vim-abolish"
rev = "v1.2"

[plugins."lspkind.nvim"]
git = "https://github.com/onsails/lspkind.nvim"
rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6"

[plugins."cutlass.nvim"]
git = "https://github.com/gbprod/cutlass.nvim"
rev = "v1.0.1"

[plugins.nvim-navic]
git = "https://github.com/smiteshp/nvim-navic"
rev = "8649f694d3e76ee10c19255dece6411c29206a54"

[plugins."ranger.nvim"]
git = "https://github.com/kelly-lin/ranger.nvim"
rev = "fd2cc999f3ef88f7cdcbcad5f26000c52b16c489"

[plugins."typescript.nvim"]
git = "https://github.com/jose-elias-alvarez/typescript.nvim"
rev = "4de85ef699d7e6010528dcfbddc2ed4c2c421467"

[plugins.nvim-spectre]
git = "https://github.com/nvim-pack/nvim-spectre"
rev = "ddd7383e856a7c939cb4f5143278fe041bbb8cb9"

[plugins."transparent.nvim"]
git = "https://github.com/xiyaowong/transparent.nvim"
rev = "8a2749a2fa74f97fe6557f61b89ac7fd873f3c21"

[plugins."icon-picker.nvim"]
git = "https://github.com/ziontee113/icon-picker.nvim"
rev = "3ee9a0ea9feeef08ae35e40c8be6a2fa2c20f2d3"

[plugins."markdown-preview.nvim"]
git = "https://github.com/iamcco/markdown-preview.nvim"
build = "cd app && npm install"
rev = "v0.0.10"

[plugins."diffview.nvim"]
git = "https://github.com/sindrets/diffview.nvim"
rev = "4516612fe98ff56ae0415a259ff6361a89419b0a"

[plugins."git-messenger.vim"]
git = "https://github.com/rhysd/git-messenger.vim"
rev = "edc603d4cda7894a743e383e16c638e206d03148"

[plugins."nvim-colorizer.lua"]
git = "https://github.com/catgoose/nvim-colorizer.lua"
rev = "ed12b5379ff203d0a15f01d71a64848b591e4adc"

[plugins."leap.nvim"]
git = "https://github.com/ggandor/leap.nvim"
rev = "67d26a13cfbf558450955ee9c76e78e03d13ee9e"

[plugins.nvim-luapad]
git = "https://github.com/rafcamlet/nvim-luapad"
rev = "v0.3"

[plugins.vim-maximizer]
git = "https://github.com/szw/vim-maximizer"
rev = "2e54952fe91e140a2e69f35f22131219fcd9c5f1"

[plugins."octo.nvim"]
git = "https://github.com/pwntester/octo.nvim"
rev = "5579f207e50cce726a2a5a460f48093ee7558fdb"

[plugins."netrw.nvim"]
git = "https://github.com/prichrd/netrw.nvim"
rev = "90501c62b9b816ed3ed1e912ae9db9af5671a1b2"

[plugins.vim-subversive]
git = "https://github.com/svermeulen/vim-subversive"
rev = "v1.0"

[plugins.vim-unimpaired]
git = "https://github.com/tpope/vim-unimpaired"
rev = "v2.1"

[plugins."copilotchat.nvim"]
git = "https://github.com/copilotc-nvim/copilotchat.nvim"
rev = "v3.3.3"
build = "make tiktoken" # Only on mac or linux
