[plugins]
nvim-lspconfig = "1.4.0"
"lazydev.nvim" = "1.9.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"

[plugins."none-ls.nvim"]
git = "https://github.com/nvimtools/none-ls.nvim"
rev = "af318216b744f2fe2d5afa6febb01f455ae61d6c"

[plugins."mason-tool-installer.nvim" ]
git = "https://github.com/whoissethdaniel/mason-tool-installer.nvim"
rev = "c5e07b8ff54187716334d585db34282e46fa2932"

[plugins."lsp-progress.nvim"]
git = "https://github.com/linrongbin16/lsp-progress.nvim"
rev = "v1.0.13"

[bundles.lsp]
items = [
  "nvim-lspconfig",
  "lazydev.nvim",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "mason-tool-installer.nvim",
  "none-ls.nvim",
  "lsp-progress.nvim"
]
