[plugins.nvim-cmp]
git = "https://github.com/hrsh7th/nvim-cmp"
rev = "v0.0.2"

[plugins.cmp_luasnip]
git = "https://github.com/saadparwaiz1/cmp_luasnip"
rev = "98d9cb5c2c38532bd9bdb481067b20fea8f32e90"

[plugins.cmp-buffer]
git = "https://github.com/hrsh7th/cmp-buffer"
rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa"

[plugins.cmp-cmdline]
git = "https://github.com/hrsh7th/cmp-cmdline"
rev = "d250c63aa13ead745e3a40f61fdd3470efde3923"

[plugins.cmp-path]
git = "https://github.com/hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"

[plugins.cmp-nvim-lsp]
git = "https://github.com/hrsh7th/cmp-nvim-lsp"
rev = "99290b3ec1322070bcfb9e846450a46f6efa50f0"

[plugins.cmp-npm]
git = "https://github.com/david-kunz/cmp-npm"
rev = "2337f109f51a09297596dd6b538b70ccba92b4e4"

[plugins.cmp-rg]
git = "https://github.com/lukas-reineke/cmp-rg"
rev = "v1.3.11"

[plugins.cmp-nuget]
git = "https://github.com/pasibergman/cmp-nuget"
rev = "6558e778e02238a898b5a6170b56f8bd7af733d7"

[plugins."copilot.vim"]
git = "https://github.com/github/copilot.vim"
rev = "v1.41.0"

[bundles.completion]
items = [
  "cmp-rg",
  "cmp-npm",
  "cmp-nvim-lsp",
  "cmp-path",
  "cmp_luasnip",
  "cmp-buffer",
  "cmp-nuget",
  "cmp-cmdline",
  "nvim-cmp",
  "copilot.vim"
]
