[plugins]
nvim-lspconfig = "1.6.0"
"lazydev.nvim" = "1.9.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"

[plugins."none-ls.nvim"]
git = "https://github.com/nvimtools/none-ls.nvim"
rev = "ed8f80849ef1ad31c2f74679fafdef7801091247"

[plugins."mason-tool-installer.nvim" ]
git = "https://github.com/whoissethdaniel/mason-tool-installer.nvim"
rev = "374c78d3ebb5c53f43ea6bd906b6587b5e899b9e"

[plugins."lsp-progress.nvim"]
git = "https://github.com/linrongbin16/lsp-progress.nvim"
rev = "v1.0.13"

[plugins."lsp-overloads.nvim"]
git = "https://github.com/issafalcon/lsp-overloads.nvim"
rev = "v1.5.0"

[bundles.lsp]
items = [
  "nvim-lspconfig",
  "lazydev.nvim",
  "mason.nvim",
  "mason-lspconfig.nvim",
  "mason-tool-installer.nvim",
  "none-ls.nvim",
  "lsp-progress.nvim",
  "lsp-overloads.nvim"
]
