[plugins]
nvim-dap = "0.9.0"
nvim-dap-ui = "4.0.0"

[plugins.one-small-step-for-vimkind]
git = "https://github.com/jbyuki/one-small-step-for-vimkind"
rev = "b9def31568d20b16f7da9479a4174d165046fe8a"

[plugins.nvim-dap-vscode-js]
git = "https://github.com/mxsdev/nvim-dap-vscode-js"
rev = "v1.1.0"

[plugins.nvim-dap-python]
git = "https://github.com/mfussenegger/nvim-dap-python"
rev = "34282820bb713b9a5fdb120ae8dd85c2b3f49b51"

[plugins."persistent-breakpoints.nvim"]
git = "https://github.com/weissle/persistent-breakpoints.nvim"
rev = "4b199b1dcfd136cac8b0fa9c8dbbdeb81463f7a9"

[plugins.nvim-dap-virtual-text]
git = "https://github.com/thehamsta/nvim-dap-virtual-text"
rev = "df66808cd78b5a97576bbaeee95ed5ca385a9750"

[bundles.debugging]
items = [
  "nvim-dap",
  "nvim-dap-ui",
  "one-small-step-for-vimkind",
  "nvim-dap-vscode-js",
  "nvim-dap-python",
  "persistent-breakpoints.nvim",
  "nvim-dap-virtual-text"
]
