[plugins]
"rocks-treesitter.nvim" = "1.3.0"
nvim-treesitter-legacy-api = "0.9.2"

[plugins.nvim-treesitter-textobjects]
git = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects"
rev = "ad8f0a472148c3e0ae9851e26a722ee4e29b1595"

[plugins.nvim-ts-context-commentstring ]
git = "https://github.com/joosepalviste/nvim-ts-context-commentstring"
rev = "1b212c2eee76d787bbea6aa5e92a2b534e7b4f8f"

[plugins.nvim-ts-autotag]
git = "https://github.com/windwp/nvim-ts-autotag"
rev = "1cca23c9da708047922d3895a71032bc0449c52d"

[bundles.syntax]
items = [
  "rocks-treesitter.nvim",
  "nvim-treesitter-legacy-api",
  "nvim-treesitter-textobjects",
  "nvim-ts-context-commentstring",
  "nvim-ts-autotag",
]
