require("utils.colorizer-plugin")
require("utils.undotree-plugin")
require("utils.maximizer-plugin")
require("utils.cheatsheet-plugin")
require("utils.indent-blankline-plugin")
require("utils.easyclip-plugin")
require("utils.icons")
